version: '3'
services:
  nats:
    image: nats
    container_name: syros-nats
    command: -m 8222
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    restart: unless-stopped
    networks:
      - local

  mongo:
    image: mongo
    container_name: syros-mongo
    command: --smallfiles
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - mongocfg:/data/configdb
    restart: unless-stopped
    networks:
      - local

  mongoclient:
    image: mongoclient/mongoclient
    container_name: syros-mongoclient
    ports:
      - 3000:3000
    volumes:
      - mongoclient:/data/db
    environment:
      - MONGO_URL=mongodb://syros-mongo:27017/mongoclient
      - MONGOCLIENT_AUTH=true
      - MONGOCLIENT_USERNAME=admin
      - MONGOCLIENT_PASSWORD=admin
    restart: unless-stopped
    networks:
      - local


networks:
  local:
    driver: bridge

volumes:
  mongodata: {}
  mongocfg: {}
  mongoclient: {}