version: '3'
services:
  nats:
    image: nats
    container_name: syros-nats
    command: -m 8222
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    restart: unless-stopped
    networks:
      - local

  mongo:
    image: mongo
    container_name: syros-mongo
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - configdb:/data/configdb
    restart: unless-stopped
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  data: {}
  configdb: {}